<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4GIAAu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4GIAAu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4GIAAu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4GIAAu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF4GIAAu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F4GIAAu',
    'container.build_id' => 'ddb3f932',
    'container.build_time' => 1589193831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4GIAAu');
